
services:
    app.browser.opener.hardprice:
        alias: 'app.browser.opener.new_session_opener.hardprice'

    app.browser.opener.existing_session_opener.hardprice:
        class: Sterlett\Browser\Opener\ExistingSessionOpener
        arguments:
            - '@app.browser.context.builder.hardprice'
            - '@app.browser.session.resumer'
            - '@app.browser.tab.actualizer'

    app.browser.opener.new_session_opener.hardprice:
        class: Sterlett\Browser\Opener\NewSessionOpener
        arguments:
            - '@app.browser.context.builder.hardprice'
            - '@app.browser.tab.actualizer'

    app.browser.context.builder.hardprice:
        class: Sterlett\Browser\Context\Builder
        arguments:
            - '@app.thread.hardprice_browsing'
            - '@app.selenium.webdriver'

    app.browser.session.resumer:
        class: Sterlett\Browser\Session\Resumer

    app.browser.refresher:
        class: Sterlett\Browser\Refresher

    app.browser.tab.actualizer:
        class: Sterlett\Browser\Tab\Actualizer

    app.browser.cleaner:
        class: Sterlett\Browser\Cleaner
