
services:
    app.browser.opener.hardprice:
        class: Sterlett\Browser\Opener
        arguments:
            - '@app.thread.hardprice_browsing'
            - '@app.selenium.webdriver'

    app.browser.refresher:
        class: Sterlett\Browser\Refresher

    app.browser.cleaner:
        class: Sterlett\Browser\Cleaner
