
services:
    app.log.logger.stdout.synchronous:
        alias: 'symfony.console.logger'

    # blocking
    symfony.console.logger:
        class: Symfony\Component\Console\Logger\ConsoleLogger
        arguments:
            - '@symfony.console.output'

    symfony.console.output:
        class: Symfony\Component\Console\Output\ConsoleOutput
