
services:
    app.request.handler:
        alias: 'app.request.handler.example_handler'
        public: true

    app.request.handler.example_handler:
        class: Sterlett\Request\Handler\ExampleHandler
        arguments:
            - '@app.log.logger.stdout'
