
services:
    app.selenium.webdriver:
        alias: 'app.bridge.itnelo.react.webdriver.selenium_hub_driver'

    app.bridge.itnelo.react.webdriver.selenium_hub_driver:
        class: Itnelo\React\WebDriver\SeleniumHubDriver
        factory: ['Itnelo\React\WebDriver\WebDriverFactory', create]
        arguments:
            - '@app.event_loop'
            -   hub:
                    host: '%selenium.hub.host%'
                    port: '%selenium.hub.port%'
                command:
                    timeout: '%selenium.command.timeout%'
                # configuration for the underlying react browser
                browser:
                    timeout: '%selenium.command.timeout%'
