
services:
    app.shutdown:
        class: Sterlett\Shutdown
        public: true
        arguments:
            - '@app.log.logger.stdout'
            - '@app.event.dispatcher'
            - '@app.event_loop'
