language: minimal

services:
    - docker

branches:
    only:
        - master
        - 0.x
        - /^\d+\.\d+\.\d+$/

before_script:
    - ls -lth
    # building services
    - docker-compose build --force-rm --no-cache
    # running tests
    - docker-compose run --rm app bin/phpunit --verbose

script:
    - docker-compose up --no-recreate --no-build --detach
    - docker-compose ps && sleep 5
    # check services are running
    - if [ -z $(docker ps -q --no-trunc | grep $(docker-compose ps -q haproxy)) ]; then docker-compose logs haproxy && exit 1; fi
    - if [ -z $(docker ps -q --no-trunc | grep $(docker-compose ps -q lighttpd)) ]; then docker-compose logs lighttpd && exit 2; fi
    - if [ -z $(docker ps -q --no-trunc | grep $(docker-compose ps -q app)) ]; then docker-compose logs app && exit 3; fi
