os:
    - linux
arch:
    - amd64
dist: bionic

language: shell

services:
    - docker

branches:
    only:
        - master
        - 0.x
        - /^\d+\.\d+\.\d+$/

env:
    global:
        - DOCKER_COMPOSE_VERSION=1.26.2
        - DOCKER_COMPOSE_URI_PATTERN=https://github.com/docker/compose/releases/download/%s/docker-compose-%s-%s

before_install:
    # setting up docker-compose
    - sudo rm /usr/local/bin/docker-compose
    - |
        sudo curl \
            -L $(printf ${DOCKER_COMPOSE_URI_PATTERN} ${DOCKER_COMPOSE_VERSION} $(uname -s) $(uname -m)) \
            -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose

before_script:
    - ls -lth
    # building services
    - bin/configure-env dev
    - docker-compose --env-file .env --file docker-compose.yml build --force-rm --no-cache haproxy lighttpd
    - |
        docker-compose --env-file .env --file docker-compose.yml build \
            --build-arg "HOST_UID=$(id -u)" \
            --force-rm \
            --no-cache \
            app
    # installing backend dependencies
    - |
        docker-compose run --rm app composer install \
            --no-scripts \
            --no-suggest \
            --classmap-authoritative \
            --ansi \
            --no-interaction
    # running backend tests
    - cp phpunit.xml.dist phpunit.xml
    - docker-compose run --rm app bin/phpunit --configuration phpunit.xml --verbose
    # applying backend configuration
    - cp config/parameters.yml.dev.dist config/parameters.yml

script:
    - docker-compose up --no-recreate --no-build --detach
    - docker-compose ps && sleep 5
    # checking load balancer is running
    - |
        if [ -z $(docker ps -q --no-trunc | grep $(docker-compose ps -q haproxy)) ]; then
            docker-compose logs haproxy
            exit 1
        fi
    # checking frontend is running
    - |
        if [ -z $(docker ps -q --no-trunc | grep $(docker-compose ps -q lighttpd)) ]; then
            docker-compose logs lighttpd
            exit 2
        fi
    # checking backend is running
    - |
        if [ -z $(docker ps -q --no-trunc | grep $(docker-compose ps -q app)) ]; then
            docker-compose logs app
            exit 3
        fi
