
# Copyright (c) 2020 Pavel Petrov <itnelo@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses>.

ARG ALPINE_VERSION=3.12
ARG NODEJS_VERSION

FROM node:${NODEJS_VERSION}-alpine${ALPINE_VERSION}

ARG TIMEZONE
ARG LIGHTTPD_VERSION

USER root

# system
RUN apk add --no-cache \
        # timezone
        tzdata \
        # lighttpd
        lighttpd=${LIGHTTPD_VERSION}

# timezone
RUN cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && \
    echo ${TIMEZONE} > /etc/timezone && \
    date

# cleanup
RUN apk del \
        # timezone
        tzdata && \
    rm -rf /var/cache/apk/*

# configurations
COPY docker/dev/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd-custom.conf

WORKDIR /var/www/localhost/htdocs
COPY --chown=lighttpd:lighttpd package.json package-lock.json rollup.config.js ./
COPY --chown=lighttpd:lighttpd src/front ./src/front
COPY --chown=lighttpd:lighttpd public ./public

# permissions
RUN chown lighttpd:lighttpd /var/www/localhost/htdocs

USER lighttpd

# dependencies
RUN npm install --no-optional

# compiling assets
RUN npm run build

RUN mkdir /var/www/localhost/htdocs/.lighttpd

CMD ["lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd-custom.conf", "2>&1"]
