
# Copyright (c) 2020 Pavel Petrov <itnelo@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses>.

ARG PHP_VERSION

FROM php:${PHP_VERSION}-cli

ARG TIMEZONE
ARG DEPLOYMENT_PATH

WORKDIR ${DEPLOYMENT_PATH}

# see .dockerignore
COPY --chown=www-data:www-data . ./

USER root

# system
RUN apt-get update && apt-get install -qy --no-install-recommends \
        # composer
        unzip

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# timezone
RUN ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && \
    echo ${TIMEZONE} > /etc/timezone && \
    printf '[PHP]\ndate.timezone = "%s"\n', ${TIMEZONE} > /usr/local/etc/php/conf.d/tzone.ini && \
    date

# xdebug
RUN pecl install xdebug-beta && docker-php-ext-enable xdebug
COPY docker/dev/app/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# pcntl
RUN docker-php-ext-install pcntl

# ds
# https://github.com/php-ds/ext-ds
RUN pecl install ds && docker-php-ext-enable ds
COPY docker/dev/app/docker-php-ext-ds.ini /usr/local/etc/php/conf.d/docker-php-ext-ds.ini

COPY docker/dev/app/php.ini /usr/local/etc/php/conf.d/php.ini

# composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer --version

# permissions
RUN chown www-data:www-data /var/www ${DEPLOYMENT_PATH}

USER www-data

# dependencies
RUN composer install --no-scripts --classmap-authoritative --ansi --no-interaction

# configurations
RUN cp config/parameters.yml.dev.dist config/parameters.yml

CMD ["bin/app"]
