
services:
    # default configuration will be applied for all services (if not explicitly specified in the target file)
    # this behavior is a result of Symfony DI logic revision, see YamlFileLoader from the "Bridge\Symfony" scope.
    _defaults:
        # automatically injects dependencies in your services
        autowire: false
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
