
services:
    app.event_loop:
        alias: 'react.event_loop.stream_select'

    # react
    react.event_loop.stream_select:
        class: React\EventLoop\StreamSelectLoop
        factory: ['React\EventLoop\Factory', create]
