
# "routines" here are callback functions, which will be executed in the event loop periodically
services:
    app.routine.price_retrieving:
        alias: 'app.routine.hardware.price.retrieving_routine'
        public: true

    app.routine.vbratio_feed:
        alias: 'app.routine.hardware.vbratio.feeding_routine'
        public: true

    app.routine.hardware.price.retrieving_routine:
        class: Sterlett\Routine\Hardware\Price\RetrievingRoutine
        arguments:
            - '@app.log.logger.stdout'
            - '@app.event_loop'
            - '@app.hardware.price.retriever.cpu'
            - '%app.routine.price.retrieving_interval%'

    app.routine.hardware.vbratio.feeding_routine:
        class: Sterlett\Routine\Hardware\VBRatio\FeedingRoutine
        arguments:
            - '@app.log.logger.stdout'
            - '@app.event_loop'
            - '@app.hardware.vbratio.feeder'
            - '%app.routine.ratio.feed_interval%'
