
services:
    app.hardprice.browser.item_searcher:
        class: Sterlett\HardPrice\Browser\ItemSearcher
        arguments:
            - '@app.retry_assistant'
            - '@app.browser.refresher'
            - '@app.hardprice.browser.item_searcher.search_bar_locator'
            - '%selenium.ajax.timeout%'
            - '%selenium.state.check_frequency%'

    app.hardprice.browser.item_searcher.search_bar_locator:
        class: Sterlett\HardPrice\Browser\ItemSearcher\SearchBarLocator
