
services:
    app.hardprice.browser.navigator:
        alias: 'app.hardprice.browser.navigator.strategy'

    app.hardprice.browser.navigator.strategy:
        class: Sterlett\HardPrice\Browser\Navigator\StrategyNavigator
        arguments:
            - !tagged_locator
                tag: 'hardprice.navigation_strategy'
                index_by: 'strategyName'
            - '%hardprice.referrer%'

    # mixin: vk
    app.hardprice.browser.navigator.strategy.vk:
        class: Sterlett\HardPrice\Browser\Navigator\ReferrerNavigator
        lazy: true
        arguments:
            - '@app.browser.tab.actualizer'
            - 'https://vk.com/hardprice'
            - '//div[contains(@class, "page_info_wrap")]//a[contains(@href, "hardprice.ru")]'
        tags:
            -   name: 'hardprice.navigation_strategy'
                strategyName: 'vk'

    # mixin: google
    app.hardprice.browser.navigator.strategy.google:
        class: Sterlett\HardPrice\Browser\Navigator\ReferrerNavigator
        lazy: true
        arguments:
            - '@app.browser.tab.actualizer'
            - 'https://google.ru/search?q=hardprice+процессоры'
            - '//span[contains(., "category › cpu")]'
        tags:
            -   name: 'hardprice.navigation_strategy'
                strategyName: 'google'

    # mixin: cy-pr
    app.hardprice.browser.navigator.strategy.cy_pr:
        class: Sterlett\HardPrice\Browser\Navigator\ReferrerNavigator
        lazy: true
        arguments:
            - '@app.browser.tab.actualizer'
            - 'https://cy-pr.com/a/hardprice.ru'
            - '//a[contains(@id, "maind")]'
        tags:
            -   name: 'hardprice.navigation_strategy'
                strategyName: 'cy-pr'

    app.hardprice.browser.navigator.strategy.direct:
        class: Sterlett\HardPrice\Browser\Navigator\DirectNavigator
        lazy: true
        arguments:
            - '@app.browser.tab.actualizer'
            - '%hardprice.authentication.base_uri%'
        tags:
            -   name: 'hardprice.navigation_strategy'
                strategyName: 'direct'
