
services:
    app.hardprice.browser.price_accumulator:
        class: Sterlett\HardPrice\Browser\PriceAccumulator
        arguments:
            - '@app.hardprice.browser.divergent'
            - '@app.hardprice.browser.item_searcher'
            - '@app.hardprice.browser.price_reader'
