
services:
    app.hardware.price.repository.cpu:
        class: Sterlett\Hardware\Price\Repository
        arguments:
            - '@app.database.connection.prices'
            - '%app.database.table_name.price%'
