
services:
    # hardprice
    app.hardware.price.provider.hardprice_provider.cpu.console.synchronous:
        class: Sterlett\Hardware\Price\Provider\BlockingProvider
        arguments:
            - '@app.hardware.price.provider.hardprice_provider.cpu'
            - '@app.event_loop'
        tags:
            -   name: 'price_provider.synchronous'
                providerId: 'HardPrice'

    # async
    app.hardware.price.provider.hardprice_provider.cpu:
        class: Sterlett\Hardware\Price\Provider\HardPriceProvider
        arguments:
            - '@app.hardware.price.provider.hardprice.id_extractor'
            - '@app.hardware.price.provider.hardprice.authenticator.guest_authenticator'
            - '@app.hardware.price.provider.hardprice.price_requester.guest'
        tags:
            -   name: 'benchmark_provider'
                providerId: 'HardPrice'

    # authenticators
    app.hardware.price.provider.hardprice.authenticator.guest_authenticator:
        class: Sterlett\Hardware\Price\Provider\HardPrice\Authenticator\GuestAuthenticator
        arguments:
            - '@app.client.hardprice'
            - '@app.hardware.price.provider.hardprice.csrf_token_parser'
            - '%hardprice.authentication_uri%'

    # requesters
    app.hardware.price.provider.hardprice.price_requester.guest:
        class: Sterlett\Hardware\Price\Provider\HardPrice\PriceRequester
        arguments:
            - '@app.client.hardprice'
            - '%hardprice.price_list_uri%'

    # extractors & parsers
    app.hardware.price.provider.hardprice.id_extractor:
        class: Sterlett\Hardware\Price\Provider\HardPrice\IdExtractor
        arguments:
            - '@app.client.hardprice'
            - '@app.hardware.price.provider.hardprice.id_parser'
            - '%hardprice.cpu.download_uri%'

    app.hardware.price.provider.hardprice.id_parser:
        class: Sterlett\Hardware\Price\Provider\HardPrice\IdParser

    app.hardware.price.provider.hardprice.csrf_token_parser:
        class: Sterlett\Hardware\Price\Provider\HardPrice\CsrfTokenParser
