
services:
    # --- hardprice
    app.hardware.price.provider.hardprice_provider.cpu.synchronous:
        class: Sterlett\Hardware\Price\Provider\BlockingProvider
        arguments:
            - '@app.hardware.price.provider.hardprice_provider.cpu.console'
            - '@app.event_loop'
        tags:
            -   name: 'price_provider.synchronous'
                providerId: 'HardPrice'

    app.hardware.price.provider.hardprice_provider.cpu.console:
        class: Sterlett\Hardware\Price\Provider\HardPrice\FallbackProvider
        arguments:
            - '@app.client.hardprice'
            - '@app.hardprice.price.fallback_parser'
            - '%hardprice.cpu.download_uri%'

    # for the microservice scope; used within an async execution flow, without progress tracking
    app.hardware.price.provider.hardprice_provider.cpu:
        class: Sterlett\Hardware\Price\Provider\HardPrice\ScrapingProvider
        arguments:
            - '@app.hardprice.item.loader.cpu'
            - '@app.hardprice.price.extractor'
            - '@app.hardprice.response.reducer'
            - '@app.hardprice.price.collector.sequential_collector'
        tags:
            -   name: 'price_provider'
                providerId: 'HardPrice'
    # ---
