
services:
    # --- hardprice
    app.hardware.price.provider.hardprice_provider.cpu.synchronous:
        class: Sterlett\Hardware\Price\Provider\BlockingProvider
        arguments:
            - '@app.hardware.price.provider.hardprice_provider.cpu.console'
            - '@app.event_loop'
        tags:
            -   name: 'price_provider.synchronous'
                providerId: 'HardPrice'

    # 'cpu' modifier is assigned by id_requester, which is configured to acquire identifiers for the CPU category
    # 'console' modifier is assigned by the reducer mixin, which is configured with a progress tracker for console env
    app.hardware.price.provider.hardprice_provider.cpu.console:
        class: Sterlett\Hardware\Price\Provider\HardPriceProvider
        arguments:
            - '@app.hardprice.id.extractor.cpu'
            - '@app.hardprice.authenticator.guest_authenticator'
            - '@app.hardprice.price.requester'
            - '@app.hardprice.response.reducer.trackable.console'
            - '@app.hardprice.price.collector.merging_collector'

    # for the microservice scope; used within an async execution flow, without progress tracking
    app.hardware.price.provider.hardprice_provider.cpu:
        class: Sterlett\Hardware\Price\Provider\HardPriceProvider
        arguments:
            - '@app.hardprice.id.extractor.cpu'
            - '@app.hardprice.authenticator.guest_authenticator'
            - '@app.hardprice.price.requester'
            - '@app.hardprice.response.reducer'
            - '@app.hardprice.price.collector.sequential_collector'
        tags:
            -   name: 'price_provider'
                providerId: 'HardPrice'
    # ---
