
services:
    app.hardware.price.retriever.cpu:
        class: Sterlett\Hardware\Price\Retriever
        arguments:
            - '@app.hardware.price.provider.hardprice.browsing_provider.cpu'
            - '@app.hardware.price.repository.cpu'
