
services:
    app.hardware.vbratio.feeder:
        alias: 'app.hardware.vbratio.feeder.database.cpu'

    app.hardware.vbratio.feeder.database.cpu:
        class: Sterlett\Hardware\VBRatio\Feeder
        arguments:
            - '@app.hardware.vbratio.provider.configurable_provider.database.cpu'
            - '@app.event.dispatcher'
