
services:
    app.hardware.vbratio.saver:
        class: Sterlett\Hardware\VBRatio\Saver
        arguments:
            - '@app.hardware.vbratio.repository'

    app.hardware.vbratio.bindings_updater:
        class: Sterlett\Hardware\VBRatio\BindingsUpdater
        arguments:
            - '@app.hardware.vbratio.repository'
