
services:
    app.hardprice.parser.id_parser:
        class: Sterlett\HardPrice\Parser\IdParser

    app.hardprice.parser.csrf_token_parser:
        class: Sterlett\HardPrice\Parser\CsrfTokenParser

    app.hardprice.parser.price_parser:
        class: Sterlett\HardPrice\Parser\PriceParser
