
services:
    app.hardprice.price.parser:
        class: Sterlett\HardPrice\Price\Parser
        arguments:
            - '@app.hardprice.price.parser.tokenizer'
            - '@app.hardprice.store.mapper'

    app.hardprice.price.parser.tokenizer:
        class: Sterlett\HardPrice\Price\Parser\Tokenizer

    # fallback
    app.hardprice.price.fallback_parser:
        class: Sterlett\HardPrice\Price\FallbackParser
        arguments:
            - '@property_accessor'
