
services:
    app.hardprice.price.parser:
        class: Sterlett\HardPrice\Price\Parser
        arguments:
            - '@app.hardprice.price.parser.tokenizer'

    app.hardprice.price.parser.tokenizer:
        class: Sterlett\HardPrice\Price\Parser\Tokenizer
