
services:
    app.hardprice.requester.id_requester.cpu:
        class: Sterlett\HardPrice\Requester\IdRequester
        arguments:
            - '@app.client.hardprice'
            - '@app.hardprice.parser.id_parser'
            - '%hardprice.cpu.download_uri%'

    app.hardprice.requester.price_requester:
        class: Sterlett\HardPrice\Requester\PriceRequester
        # non-shared, because of available authentication options at instance-level; so, a part of behavior can be
        # changed at runtime, by the user-side (which breaks default, "singleton" contract from DI container) and must
        # not be shared by default
        shared: false
        arguments:
            - '@app.client.hardprice'
            - '%hardprice.price_list_uri%'
