
services:
    app.request.uri.matcher:
        alias: 'app.request.uri.matcher.path_normalizing_matcher.hardware_mark'

    app.request.uri.matcher.path_normalizing_matcher.hardware_mark:
        class: Sterlett\Request\Uri\Matcher\PathNormalizingMatcher
        arguments:
            - '@app.request.uri.matcher.array_matcher.hardware_mark'
            - '@app.request.uri.normalizer.path_prefix_normalizer'

    app.request.uri.matcher.array_matcher.hardware_mark:
        class: Sterlett\Request\Uri\Matcher\ArrayMatcher
        arguments:
            -   /cpu/list.json: 'app.request.handler.action.cpu_list_action'
            -   /cpu/deals.json: 'app.request.handler.action.cpu_deals_action'
