
services:
    app.request.uri.matcher:
        alias: 'app.request.uri.matcher.array_matcher.hardware_mark'
        public: true

    app.request.uri.matcher.array_matcher.hardware_mark:
        class: Sterlett\Request\Uri\Matcher\ArrayMatcher
        arguments:
            -   /cpu/list.json: 'app.request.handler.action.cpu_list_action'
